config:
  send_anonymous_usage_stats: False
  use_colors: True
nba_monte_carlo:
  target: dev
  outputs:
    dev:
      type: duckdb
      threads: 4
      path: nba_monte_carlo.duckdb
      remote:
        host: 0.0.0.0
        port: 5433
        user: jacob